### ISSUE TITLE
FilterShipMMSI not working as expected

### ISSUE THREAD

**Issue by Corey-Wademan** [aisstream/aisstream#2]
When using FilterShipMMSI, I would expect the behavior would be to only filter for the specified MMSI's but it doesn't appear that is the case. It will give my a response with all the vessels within the bounding boxes I specified. Should bounding boxes be excluded?

**Comment by aisstream** [comment]
I believe the property is `FiltersShipMMSI` not `FilterShipMMSI` which I admit is confusing. Could you let me know if that change works?

**Comment by Corey-Wademan** [comment]
Seems like that was the issue. Thank you! Is there a list of the AIS stations that the websocket pulls from or a map of the vessel coverage?
