### ISSUE TITLE
metadata returning 0 for MMSI

### ISSUE THREAD

**Issue by jliebrand** [aisstream/aisstream#3]
Something appears to have recently changed, but the metadata is no longer reporting the correct MMSI. It reports 0 (zero) for all messages:

example:
...
    "MessageType": "StandardClassBPositionReport",
    "MetaData": {
        "MMSI": 0,
        "MMSI_String": 0,
        "ShipName": "LEONORA",
        "latitude": 58.907885,
        "longitude": 17.971574999999998,
        "time_utc": "2023-07-25 20:33:29.264157289 +0000 UTC"
    }

**Comment by aisstream** [comment]
Hello, we have identified and deployed a fix for the issue. See https://github.com/aisstream/issues/issues/36 for further details. 

I will close this issue I favour of tracking the bug there.
